apiVersion: projectsame.io/v1alpha1
metadata:
    name: CrossSellPrediction
    version: 0.0.0
workflow:
    type: kubeflow
    parameters:
        kubeflowVersion: 1.2
        kubeflowNamespace: kubeflow # Only support Kubeflow namespace
        credentialFile: porter-kfp
pipeline:
    name: "training"
    description: "An example pipeline that trains a model to perform cross-sell prediction"
    package: "pipelines/pipeline-dev.tar.gz"
run:
    name: "default"
    parameters:
        epochs: 10
