name: run

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2
      - name: install tool binaries
        shell: bash
        run: |
          curl -sfL https://get.sameproject.org | bash -
          curl -s https://toolkit.fluxcd.io/install.sh | sudo bash
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo mv ./kubectl /usr/local/bin/kubectl
      - name: setup credentails
        shell: bash
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          cat ~/.kube/config
          mkdir -p ~/.same
          touch ~/.same/config
          echo "activecontext: " >> ~/.same/config.yaml
      - name: bootstrap flux
        shell: bash
        run: |
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          flux bootstrap github --owner=chanwit --repository=emas-ci --token-auth --path=cluster
      - name: run same program
        shell: bash
        run: |
          same program run --file same.yaml --experiment-name "${{ github.repository }}" --run-name "${{ github.sha }}"`
